### ISSUE TITLE
Linux標準教科書

### ISSUE THREAD

**Issue by sakamohy** [sakamohy/menta#1]

**Comment by sakamohy** [comment]
昨日は、linux教科書の6のviエディタのところまで進みました。
linuxの基礎は一回勉強したことがあったので良い復習の機会になりました。
わからないところは今のところありません。
今日は、６以降に取り掛かる予定です。

**Comment by sakamohy** [comment]
昨日は、6以降に取り掛かりました。
疑問に思った点がいくつかあったので記載します。

・network.serviceとNetworkMannagerの違い
・sysconfigとconfigの違い
・プロセスというのは、サービスがメモリーに上がっている状態のことで間違いないですか？
・ＣＤ/DVDなどの外部ドライブをマウントする場合、
１．まず、外部ドライブのパーティションを決める。
２．ファイルシステム用とスワップ用の2つのパーティションを決める。
３．ファイルシステム用のパーティションにファイルシステムを採用し、マウントする。
この手続きであっているでしょうか？

**Comment by RVIRUS0817** [comment]
ここらへんはオンプレの話なので無視しちゃって大丈夫です〜
プロセスは各サービスの子みたいなものなので、cpuやメモリーに依存します。なのでチューニング等をすればメモリーの消費率なども考えてサービスを作る必要があります。
