### ISSUE TITLE
[課題# 1]VagrantでWordpress環境を作る

### ISSUE THREAD

**Issue by RVIRUS0817** [sakamohy/menta#2]
## 要件

Vagrantをインストール
イメージはCentOS7
mentaユーザーの作成とssh公開鍵認証をする
Apache/Nginx/H2Oのインストール それぞれの設定と比較
https オレオレ証明書でアクセスできるように
PHP7最新のインストールと設定
Mysql最新のインストールと設定
Wordpress最新のインストール
menta.meでアクセスできるようにする

**Comment by RVIRUS0817** [comment]
@sakamohy 
まずは調べながら進めていってもらえばと思います👍

**Comment by sakamohy** [comment]
Vagrantをインストールしてmentaユーザーでのssh公開鍵認証を行いました。
今回は、Vagrantをインストールしたwindowsで秘密鍵と公開鍵を作成し、公開鍵をvagrantの仮想サーバーに設置しました。
windowsの.ssh下のコンフィグファイルの中身
これで、
　　` Host vm
         HostName 192.168.33.10
         User menta
         IdentityFile `C:\Users\sakah\.ssh\id_rsa`
仮想サーバー側のmentaユーザーディレクトリの.ssh下に公開鍵設置
`-rw------- 1 menta menta 576 Sep 28 20:08 authorized_keys`

これで
`ｓｓｈ　ｖｍ`
とwindowsで打つと、仮想サーバーにアクセスできる。

**Comment by sakamohy** [comment]
Apache/nginx/h2oそれぞれの設定

Apache
`Listen 80　　DocumentRoot "/var/www/html"`

**Comment by sakamohy** [comment]
オレオレ認証のよるhttps通信
まずは、mod_sslを追加
`[root@localhost conf.d]# yum install mod_ssl`
秘密鍵の作成
`[root@localhost conf]# openss;l genrsa -des3 -out server.key 2048`
証明書署名要求作成
`openssl genrsa req -new -key server.key -out server.csr`
サーバー証明書を自分の秘密鍵で署名
`openssl x509 -days 3650 -req -singnkey server.key < server.csr > server.crt`
apacheの設定ファイルの下に配置
`-rw-r--r-- 1 root root 11753 Aug  6 14:44 httpd.conf `  
`-rw-r--r-- 1 root root 13077 Aug  8 12:42 magic`
`-rw-r--r-- 1 root root  1216 Oct  8 23:33 server.crt`  
`-rw-r--r-- 1 root root  1009 Oct  8 23:30 server.csr ` 
`-rw-r--r-- 1 root root  1751 Oct  8 23:26 server.key `
ssl.confの設定
`SSLCertificateFile /etc/httpd/conf/server.crt`
`SSLCertificateKeyFile /etc/httpd/conf/server.key`

**Comment by sakamohy** [comment]
phpインストール
レポジトリ追加
` yum -y install http://rpms.famillecollet.com/enterprise/remi -release-7.rpm`
phpインストール
`yum -y install --ebnabledrepo=ewmi,ewmieremi-php73 
php php-devel ph p-mbstring php-pdo php-gd php-xml`
`yum install --enabledrepo=remi,remi-php6556 php-mcrypt php-mysq l`
phpの設定
```
expose_php = Off
post_max_size = 20M
upload_max_filesize = 20M
date.timezone = "Asia/Tokyo"
mbstring.language = Japanese
mbstring.internal_encoding = UTF-8
mbstring.http_output = pass
mbstring.encoding_translation = On
mbstring.detect_order = auto
mbstring.substitute_character = none
```
![php](https://user-images.githubusercontent.com/55516949/66714343-95a40880-edf0-11e9-908e-8229b1d2c46e.png)

**Comment by sakamohy** [comment]
mysqlのレポジトリの追加
`  yum localinstall http://dev.mysql.com/get/mysql157-community-release-el7-7.noarch.rpm57-community-release-el7-7.noarch.rpm`
ダウンロード
`yum install -y mysql-community-server`
その後新しくパスワードを設定し、文字コートの設定。
```
mysql> exitshow variables like "chara%";
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```
文字コード設定完了

**Comment by sakamohy** [comment]
wordpressのファイルを/www/html/下にダウンロード
`wget https://ja.wordpress.org/latest-ja.tar.gz`
開く
`tar zxvf latest-ja.tar.gz`
ファイルの中身を/www/html下に移動
`[root@localhost wordpress]# mv * ./..`

sql設定
データベース追加
```
mysql> Create CREATE DATABASE wpdb

mysql> SHOW DATEDATABASES
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| wpdb               |
+--------------------+
```
mentaユーザー追加
```
mysql> MariaDB [mysql]> SELECT user, host from user;
+---------------+-----------+
| user          | host      |
+---------------+-----------+
| menta         | localhost |
| mysql.session | localhost |
| mysql.sys     | localhost |
| root          | localhost |
```
wp-config-sample.php編集
```
// ** MySQL 設定 - この情報はホスティング先から入手してください。 ** //
/** WordPress のためのデータベース名 */
define('DB_NAME', 'wpdb');

/** MySQL データベースのユーザー名 */
define('DB_USER', 'menta');

/** MySQL データベースのパスワード */
define('DB_PASSWORD', '＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊');

/** MySQL のホスト名 */
define('DB_HOST', 'localhost');

```



![ログイン](https://user-images.githubusercontent.com/55516949/66714735-752a7d00-edf5-11e9-81d7-70cee0511e4b.png)
![ログイン画面](https://user-images.githubusercontent.com/55516949/66714736-7b205e00-edf5-11e9-8700-e54eb244af98.png)
