### ISSUE TITLE
質問コーナー

### ISSUE THREAD

**Issue by sakamohy** [sakamohy/menta#3]

**Comment by sakamohy** [comment]
yumで行うパッケージとレポジトリの関係がいまいちわかりません。
自分のイメージでは、
**パッケージというのはプログラムの塊で、OSにそのプログラムを追加していくことで機能を拡張することができる。
レポジトリはプログラムがある場所で、レポジトリをOSに追加することで、OSがパッケージを取ってくる場所が増えて、様々なパッケージをOSに追加できる。**
このようなイメージなのですが、どうでしょうか？

**Comment by RVIRUS0817** [comment]
パッケージは
`/etc/yum.repos.d/` 配下でデフォルトのパッケージが管理されていますが、
特定ミドルウェアや最新のリポジトリはデフォルトのパッケージで管理されていません。
なので、リポジトリを追加することで、新しいミドルウェアなどがインストールできるようになります。
こんなイメージですかね🙆🏻‍♂️
