### ISSUE TITLE
menta.meでアクセス

### ISSUE THREAD

**Issue by sakamohy** [sakamohy/menta#4]

**Comment by sakamohy** [comment]
menta.meでアクセス
前回は、Apacheを使用したので今回はnginxを使用。
nginxの設定ファイル

```server {
    listen       880;
    server_name  localhost;
    charset utf-8;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/blog/nginxpress ;
        index  index.php;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        root           /usr/share/nginx/blog/nginxpress ;
        fastcgi_pass   unix:/run/php-fpm/php5-fpm.sock;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root/$fastcgi_script_name;
        include        fastcgi_params;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    # location ~ /\.ht {
    #    deny  all;
    # }
}
 ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    server {
         listen 443 ssl;
         server_name localhost;
         ssl_certificate /etc/nginx/conf.d/server.crt;
         ssl_certificate_key /etc/nginx/conf.d/server.key;

         charset utf-8;

    location /{
        root   /usr/share/nginx/blog/nginxpress ;
        index  index.php;
    }
    location ~ \.php$ {
        root           /usr/share/nginx/blog/nginxpress ;
        fastcgi_pass   unix:/run/php-fpm/php5-fpm.sock;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root/$fastcgi_script_name;
        include        fastcgi_params;
    }

}
```

**Comment by sakamohy** [comment]
php-fpmの設定ファイル　一部
‘‘‘; Start a new pool named 'www'.
; the variable $pool can be used in any directive and will be replaced by the
; pool name ('www' here)
[www]

; Per pool prefix
; It only applies on the following directives:
; - 'access.log'
; - 'slowlog'
; - 'listen' (unixsocket)
; - 'chroot'
; - 'chdir'
; - 'php_values'
; - 'php_admin_values'
; When not set, the global prefix (or @php_fpm_prefix@) applies instead.
; Note: This directive can also be relative to the global prefix.
; Default Value: none
;prefix = /path/to/pools/$pool

; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
; RPM: apache user chosen to provide access to the same directories as httpd
user = nginx
; RPM: Keep a group allowed to write in log dir.
group = nginx

; The address on which to accept FastCGI requests.
; Valid syntaxes are:
;   'ip.add.re.ss:port'    - to listen on a TCP socket to a specific IPv4 address on
;                            a specific port;
;   '[ip:6:addr:ess]:port' - to listen on a TCP socket to a specific IPv6 address on
;                            a specific port;
;   'port'                 - to listen on a TCP socket to all addresses
;                            (IPv6 and IPv4-mapped) on a specific port;
;   '/path/to/unix/socket' - to listen on a unix socket.
; Note: This value is mandatory.
listen = /run/php-fpm/php5-fpm.sock
; Set listen(2) backlog.
; Default Value: 511
;listen.backlog = 511

; Set permissions for unix socket, if one is used. In Linux, read/write
; permissions must be set in order to allow connections from a web server.
; Default Values: user and group are set as the running user
;                 mode is set to 0660
listen.owner = nginx
listen.group = nginx
...etc
```
user group listen.owner listen.group をnginxに変更

**Comment by sakamohy** [comment]
wp-config.php
```
// ** MySQL 設定 - この情報はホスティング先から入手してください。 ** //
/** WordPress のためのデータベース名 */
define( 'DB_NAME', 'wpdb2' );

/** MySQL データベースのユーザー名 */
define( 'DB_USER', 'menta.me' );

/** MySQL データベースのパスワード */
define( 'DB_PASSWORD', 'Tomirehyu-7859' );

/** MySQL のホスト名 */
define( 'DB_HOST', 'localhost' );
```

**Comment by sakamohy** [comment]
![menta me login](https://user-images.githubusercontent.com/55516949/67166270-d12e6c00-f3c8-11e9-8549-e523a7dc5667.png)

![nginxhpome](https://user-images.githubusercontent.com/55516949/67166272-d7bce380-f3c8-11e9-9516-3fc53e3ee730.png)

**Comment by sakamohy** [comment]
しかし、https通信で行うと、
![ssl menta me](https://user-images.githubusercontent.com/55516949/67166306-18b4f800-f3c9-11e9-94d0-f1ed18db9c06.png)

![ssl nothome](https://user-images.githubusercontent.com/55516949/67166309-1d79ac00-f3c9-11e9-92e3-ab00fd2e69a3.png)

こうなってしまい、プロトコルはhttpsなのにポート番号880がついてきてしまい、アクセスできなくなってしまいます。何が原因でしょうか？
回答よろしくお願いします。

**Comment by RVIRUS0817** [comment]
これはペアプロしましょう！
